<table>
    <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Date de Création</th>
            <th scope="col">Image</th>
            <th scope="col" colspan="2">Actions</th>
        </tr>
    </thead>
    <?php foreach ($allArticles as $article): ?>
        <tr id="article-<?=$article['id']?>">
            <td><?=$article['title'];?></td>
            <td><?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></td>
            <td>   
                <?php if ($article['image']): ?>
                    <img src="images/<?=$article['image'];?>" alt="">
                <?php endif; ?>
            </td>
            <td>
                <a href="edit_article.php?id=<?=$article['id']?>"><i class="fa-solid fa-pen-to-square"></i> Modifier</a>
                <a class="delete_article_button" href="delete_article.php?id=<?=$article['id']?>" data-ajax="delete_article_ajax.php?id=<?=$article['id']?>">
                    <i class="fa-solid fa-trash-can"></i> Supprimer
                </a>
            </td>
        </tr>    
    <?php endforeach; ?>
</table>
