<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$title; ?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <?php if (isset($script)):?>
        <?=$script;?>
    <?php endif;?>
</head>
<body>
    <nav>
        <?php if (isConnected()): ?>
            <p><i class="fa-solid fa-user"></i> <?=htmlspecialchars($_SESSION['user']['firstname'])?> <?=htmlspecialchars($_SESSION['user']['lastname'])?></p>
            <a href="../public/logout.php">Déconnexion</a>
        <?php else : ?>
            <a href="../public/login.php">Connexion</a>
            <a href="../public/signup.php">Créer un compte</a>
        <?php endif; ?>
    </nav>  
    <main>
        <?php
            include '../templates/'.$template.'.phtml';
        ?>
    </main>
</body>
</html>