<form method="POST" action="login.php">
    <fieldset>
        <div>
            <label for="email">Email</label>
            <input type="text" id="email" name="email"></textarea>
        </div>
        <div>
            <label for="password">Mot de Passe</label>
            <input type="text" id="password" name="password">
        </div>
        <input type="submit" value="Valider">
    </fieldset>
</form>
<?php if (isset($error)): ?>
    <p class="error"><?=$error;?></p>
<?php endif; ?>