
<form method="POST" action="signup.php">
    <fieldset>
        <div>
            <label for="firstname">Prénom</label>
            <input type="text" id="firstname" name="firstname">
        </div>
        <div>
            <label for="lastname">Nom</label>
            <input type="text" id="lastname" name="lastname">
        </div>
        <div>
            <label for="email">Email</label>
            <input type="text" id="email" name="email"></textarea>
        </div>
        <div>
            <label for="password">Mot de Passe</label>
            <input type="text" id="password" name="password">
        </div>
        <div>
            <label for="password-confirm">Confirmez le Mot de Passe</label>
            <input type="text" id="password-confirm" name="password-confirm">
        </div>
        <input type="submit" value="Enregistrer">
    </fieldset>
</form>

<?php if (isset($errors)): ?>
    <?php foreach ($errors as $error): ?>
        <p class="error"><?=$error;?></p>
    <?php endforeach; ?>
<?php endif; ?>