<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="index.php">
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" name="firstname">
        <input type="submit" value="Bonjour !">
    </form>
    <?php if ($firstname != null): ?>
    <p>Bonjour <?=$firstname;?></p>
    <?php endif; ?>
</body>
</html>