<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Un Article</title>
</head>
<body>
    <main>
        <h1>Mon Blog</h1>
        <fieldset>
            <legend> <?=$article['title'];?> </legend>
            <div>
                <p><?=$article['content'];?></p>
            </div>
            <div>
                <?php if ($article['image']): ?>
                    <img src="images/<?=$article['image'];?>" alt="">
                <?php endif; ?>
            </div>
            <div>
                <small>Créé le <?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></small>
            </div>
        </fieldset>
    </main>
</body>
</html>