<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <main>
        <h1>Mon Blog</h1>
        <?php foreach ($allArticles as $article): ?>
            <fieldset>
                <legend> <?=$article['title'];?> </legend>
                <div>
                    <em><?=$article['abstract']?$article['abstract']:substr($article['content'], 0, 150). ' [...]'; ?></em>
                </div>
                <div>
                    <?php if ($article['image']): ?>
                        <img src="images/<?=$article['image'];?>" alt="">
                    <?php endif; ?>
                </div>
                <div>
                    <small>Créé le <?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></small>
                </div>
                <a href="article.php?id=<?=$article['id'];?>">Lire la suite</a>
            </fieldset>
        <?php endforeach; ?>
    </main>
</body>
</html>
