<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abonnement</title>
</head>
<body>
    <form method=POST action="index.php">
        <label for="email">Votre email</label>
        <input type="text" id="email" name="email">
        <input type="submit" value="VALIDER">
    </form>
    <?php if ($error != null):?>
        <p class="error"><?=$error;?></p>
    <?php endif;?>
</body>
</html>